# MONTH 10 — Geography & World

FACT_OR_FAKE=[
("Russia is so large it spans 11 time zones.",True,"Russia is the largest country by area and covers 11 different time zones."),
("Australia is the only country that is also a continent.",True,"Australia is unique in being both a country and its own continent."),
("The Amazon River discharges more freshwater than the next seven largest rivers combined.",True,"The Amazon accounts for approximately 20% of all freshwater discharged into the oceans globally."),
("The Dead Sea is the lowest point on Earth's land surface.",True,"At roughly 430 metres below sea level, the Dead Sea is Earth's lowest land surface point."),
("Canada has more lakes than the rest of the world combined.",True,"Canada contains about 60% of the world's lakes, with estimates exceeding 2 million."),
("The Pacific Ocean is larger than all of Earth's landmass combined.",True,"The Pacific Ocean covers about 165 million km², more than all the continents put together."),
("China shares a border with more countries than any other nation.",False,"Russia shares land borders with 14 countries — the same count as China, tied for most."),
("The Nile River flows northward.",True,"The Nile flows south to north, emptying into the Mediterranean Sea in northern Egypt."),
("New Zealand was the last large habitable land on Earth to be settled by humans.",True,"The Māori arrived around 1280 AD, making New Zealand one of the last major landmasses to be settled."),
("Iceland is covered mostly in ice and Greenland is mostly green.",True,"Iceland has relatively mild coasts due to the Gulf Stream, while much of Greenland is ice sheet."),
("The Great Barrier Reef is visible from space.",True,"The reef is around 2,300 km long, making it visible from low orbit."),
("Vatican City has no permanent residents.",False,"Vatican City has several hundred permanent residents, including clergy, the Swiss Guard, and service workers."),
("Mount Everest grows taller every year due to tectonic activity.",True,"The Indian and Eurasian plates continue to push together, adding approximately 4mm to Everest's height annually."),
("The Sahara Desert is getting larger due to desertification.",True,"The Sahara has expanded southward by roughly 10% since 1920 due to climate change and land use."),
("Brazil is the only Portuguese-speaking country in South America.",True,"All other South American countries speak Spanish as their primary language, except for Brazil."),
("The capital of Australia is Sydney.",False,"The capital of Australia is Canberra, which was purpose-built as a compromise between Sydney and Melbourne."),
("The world's smallest country is Monaco.",False,"Vatican City, at 0.44 km², is smaller than Monaco."),
("The Mississippi River flows south into the Gulf of Mexico.",True,"The Mississippi begins in Minnesota and flows southward for approximately 3,730 km to the Gulf of Mexico."),
("More than half of the world's countries are in the Southern Hemisphere.",False,"The majority of countries are in the Northern Hemisphere; only around 30-35 countries lie mostly south of the equator."),
("Finland has more saunas than cars.",True,"Finland has approximately 3.3 million saunas for a population of 5.5 million — more than the number of registered cars."),
("The Atacama Desert in South America receives virtually no rain.",True,"Some parts of the Atacama haven't seen measurable rainfall in centuries, making it the driest non-polar desert."),
("The Caspian Sea is technically the world's largest lake.",True,"The Caspian Sea, although called a sea, is landlocked and classified by some geographers as a lake."),
("Nepal and China share the summit of Mount Everest.",True,"The border runs roughly through the summit, meaning both countries can technically claim Everest's peak."),
("The Danube River flows through more countries than any other river.",True,"The Danube passes through or borders 10 countries in Europe — more than any other river."),
("Antarctica has no permanent human population but does have permanent research stations.",True,"No indigenous population lives in Antarctica, but around 1,000–5,000 researchers live there depending on the season."),
("The population of Tokyo is greater than the entire population of Canada.",True,"Greater Tokyo has over 37 million people; Canada's population is approximately 38–40 million — very close."),
("Every country in the world has at least one mountain.",False,"Countries like Bangladesh, Maldives, and parts of the Netherlands are almost entirely flat with no mountains."),
("Lake Baikal contains more freshwater than all of North America's Great Lakes combined.",True,"Lake Baikal holds approximately 23% of the world's surface freshwater — more than the five Great Lakes together."),
("The equator passes through 13 countries.",True,"The equator crosses through Ecuador, Colombia, Brazil, São Tomé & Príncipe, Gabon, Congo, DRC, Uganda, Kenya, Somalia, Maldives, Indonesia, and Kiribati."),
("The world's longest coastline belongs to Canada.",True,"Canada's coastline measures approximately 202,080 km — the longest of any country."),
]

QUIZZES=[
("What is the capital of Japan?",["Osaka","Tokyo","Kyoto"],1),
("On which continent is the Sahara Desert located?",["Asia","Africa","Australia"],1),
("Which is the longest river in South America?",["Orinoco","Amazon","Paraná"],1),
("What is the capital of Brazil?",["São Paulo","Rio de Janeiro","Brasília"],2),
("Which country is home to the most pyramids in the world?",["Egypt","Mexico","Sudan"],2),
("What is the smallest country by area in the world?",["Monaco","San Marino","Vatican City"],2),
("Which mountain range runs through the western side of South America?",["Rocky Mountains","Himalayas","Andes"],2),
("What is the capital of South Africa?",["Cape Town","Johannesburg","Pretoria"],2),
("Which ocean is the largest by area?",["Indian Ocean","Atlantic Ocean","Pacific Ocean"],2),
("What is the capital of Canada?",["Toronto","Vancouver","Ottawa"],2),
("Which country has the most UNESCO World Heritage Sites?",["China","France","Italy"],2),
("What is the longest wall ever built?",["Hadrian's Wall","Great Wall of China","Berlin Wall"],1),
("In which country is the Serengeti National Park?",["Kenya","South Africa","Tanzania"],2),
("Which country is home to the world's most active volcano, Kilauea?",["Hawaii, USA","Iceland","Indonesia"],0),
("What is the official language of Brazil?",["Spanish","Portuguese","French"],1),
("What is the capital of India?",["Mumbai","New Delhi","Kolkata"],1),
("What is the tallest active volcano in the world?",["Kilimanjaro","Ojos del Salado","Mauna Loa"],1),
("Which sea separates Europe from Africa at their closest point?",["Red Sea","Strait of Gibraltar","Mediterranean Sea"],2),
("What is the capital of Nigeria?",["Lagos","Abuja","Kano"],1),
("Which country has the most active volcanoes?",["Japan","Iceland","Indonesia"],2),
("What is the capital of Australia?",["Sydney","Melbourne","Canberra"],2),
("Which is the only sea without any coastline?",["Sargasso Sea","Red Sea","Dead Sea"],0),
("What is the capital of Sweden?",["Oslo","Copenhagen","Stockholm"],2),
("Which country is home to the most UNESCO World Heritage Sites?",["China","France","Italy"],2),
("What is the deepest lake in the world?",["Lake Superior","Lake Baikal","Caspian Sea"],1),
("Which country has the longest land border in the world?",["China","USA","Canada"],2),
("Which country has the most natural hot springs?",["Japan","Iceland","New Zealand"],0),
("What is the largest country in Africa by area?",["Sudan","Algeria","Democratic Republic of Congo"],1),
("What is the capital of Saudi Arabia?",["Riyadh","Jeddah","Mecca"],0),
("Which is the flattest country on Earth?",["Netherlands","Maldives","Bangladesh"],1),
]

WYR=[
("Live on every continent for 1 month each","Visit every country in the world for 1 week each"),
("Speak every European language fluently","Speak every Asian language fluently"),
("Own a house in Tokyo","Own a house in Paris"),
("Spend a year in the Amazon rainforest","Spend a year in the Sahara Desert"),
("Visit every capital city in the world","Visit every national park in the world"),
("Explore the Sahara by camel","Explore Antarctica by dogsled"),
("Live on a remote Pacific island for a year","Live in a remote mountain village in Nepal for a year"),
("Have been born in Norway","Have been born in New Zealand"),
("Sail around the world solo","Drive across every country in Asia"),
("Spend a week in Iceland in summer (midnight sun)","Spend a week in Iceland in winter (northern lights)"),
("Know the exact location of every country on a map","Know every country's capital city from memory"),
("Go on safari in Kenya","Go scuba diving on the Great Barrier Reef"),
("Witness the Northern Lights in person","Witness a total solar eclipse in person"),
("Have a private cabin in the Swiss Alps","Have a private villa on a Greek island"),
("Explore the ancient ruins of Rome","Explore the ancient ruins of Machu Picchu"),
("Hike the Great Wall of China","Hike the Inca Trail to Machu Picchu"),
("Visit every wonder of the ancient world (if they still existed)","Visit every wonder of the modern world"),
("Own an island in the Pacific","Own a private mountain in the Rockies"),
("Spend a year living in Japan","Spend a year living in Brazil"),
("See every landmark on Earth from a satellite","Stand on every highest point in every country"),
("Swim in every ocean on Earth","Climb the highest peak on every continent"),
("Live near the equator forever","Live near the Arctic forever"),
("Have perfect knowledge of world geography","Have perfect knowledge of every world history event"),
("Only travel by boat for the rest of your life","Only travel by train for the rest of your life"),
("Spend a week exploring the jungle","Spend a week exploring underwater caves"),
("Have a house that teleports to any city every morning","Have a boat that can sail anywhere in the world instantly"),
("Know the population of every city on Earth","Know the exact distance between any two points on Earth"),
("Move to a new country every year for 10 years","Stay in one country your whole life and master it completely"),
("See sunrise from the top of Kilimanjaro","See sunrise from the top of the Eiffel Tower"),
("Have a private map of every hidden cave system on Earth","Have a private map of every undiscovered shipwreck on Earth"),
]

if __name__=="__main__":
    print("FoF:",len(FACT_OR_FAKE),"| Quiz:",len(QUIZZES),"| WYR:",len(WYR))
