# MONTH 8 — History & Culture

FACT_OR_FAKE=[
("The Great Wall of China took over 1,000 years to build.",True,"Construction spanned from the 7th century BC to the 17th century AD — over 1,000 years of various dynasties building and extending it."),
("Julius Caesar was born by caesarean section.",False,"The 'Caesarean' name likely comes from a Latin root — Caesar's mother survived his birth, which would not have happened if C-sections were performed then."),
("The ancient Egyptians used toothpaste.",True,"They used a paste made from crushed rock salt, mint, dried iris flower, and pepper."),
("Vikings wore horned helmets.",False,"No archaeological evidence supports horned Viking helmets — that's a 19th-century myth popularized by artists."),
("The Trojan War was entirely fictional with no historical basis.",False,"Archaeological evidence at Hisarlik in Turkey suggests a real conflict around 1200 BC that likely inspired the legend."),
("Cleopatra was Egyptian by blood.",False,"Cleopatra was of Macedonian Greek descent, from the Ptolemaic dynasty."),
("Ancient Greeks had a word for being bored.",False,"Ancient Greek had no single word equivalent to modern boredom — the concept as we know it emerged much later."),
("The Black Death was caused by a bacterium, not a virus.",True,"The Black Death was caused by Yersinia pestis, a bacterium spread by fleas on rats."),
("Napoleon was unusually short for his time.",False,"He stood around 5'7'' — average for a French man of his era. The myth came partly from a British propaganda nickname."),
("The Eiffel Tower was built as a permanent Parisian landmark.",False,"It was originally intended to be a temporary structure for the 1889 World's Fair and was nearly demolished."),
("Ancient Romans used urine as a mouthwash.",True,"The ammonia in urine was valued as a cleaning agent, and Roman toothpaste and mouthwash recipes included it."),
("King Tutankhamun died in battle.",False,"Evidence suggests he died from complications of malaria combined with a broken leg, likely not in battle."),
("The first printed book was the Gutenberg Bible.",True,"Johannes Gutenberg's Bible, printed around 1455, is considered the first major book printed using movable type in Europe."),
("Ancient Mayans invented the concept of zero.",True,"The Maya independently developed a positional number system that included zero, around the 4th century AD."),
("The Statue of Liberty was originally intended for Egypt.",True,"The sculptor Frédéric Auguste Bartholdi originally pitched a similar design to Egypt for the Suez Canal before proposing it to the USA."),
("The hundred years war lasted exactly 100 years.",False,"The Hundred Years' War lasted 116 years, from 1337 to 1453."),
("Ancient Greeks invented the first alarm clock.",True,"Ctesibius of Alexandria invented a water clock that could ring an alarm, around 250 BC."),
("Marie Curie is the only person to have won Nobel Prizes in two different sciences.",True,"She won the Nobel Prize in Physics (1903) and Chemistry (1911)."),
("The first Olympics only allowed married women to compete.",False,"Married women were actually forbidden from attending or competing; only unmarried women could attend certain events."),
("The Wright Brothers' first flight lasted less than a minute.",True,"Orville Wright's first controlled flight at Kitty Hawk in 1903 lasted just 12 seconds."),
("Ancient Egyptians shaved their eyebrows when their cat died.",True,"As a sign of mourning for the sacred animal, family members would shave their eyebrows."),
("The word 'salary' comes from 'sal', the Latin word for salt.",True,"Roman soldiers were sometimes paid in salt, giving us the word 'salary'."),
("The first woman to run for U.S. President did so before women could vote.",True,"Victoria Woodhull ran for president in 1872, nearly 50 years before women's suffrage was granted."),
("Shakespeare invented over 1,700 words still used in English today.",True,"Words like 'bedroom', 'lonely', 'generous', and 'gloomy' are among those attributed to Shakespeare."),
("The Colosseum in Rome was used as a quarry in the Middle Ages.",True,"Romans recycled its travertine stone for other buildings, taking roughly 100,000 tonnes of material."),
("Christopher Columbus was trying to prove the Earth was round.",False,"Educated people already knew the Earth was round — Columbus was trying to find a western sea route to Asia."),
("Ancient Spartans used iron bars as currency to discourage hoarding wealth.",True,"Spartans deliberately used heavy, impractical iron bars to make wealth accumulation difficult."),
("The Black Death killed fewer than 10% of Europe's population.",False,"The Black Death killed an estimated 30–60% of Europe's population in the 14th century."),
("The term 'assassin' comes from an Arabic word related to hashish.",True,"The word derives from 'hashishin', a name given to the Nizari Ismailis, though the drug link is historically disputed."),
("Medieval peasants had no concept of vacation or leisure time.",False,"Medieval peasants had numerous religious feast days and market days that served as communal rest and celebration."),
]

QUIZZES=[
("In which country was the Eiffel Tower built?",["Italy","France","Spain"],1),
("Which ancient wonder was located in Alexandria, Egypt?",["The Hanging Gardens","The Great Lighthouse","The Colossus"],1),
("What year did World War II end?",["1943","1945","1947"],1),
("Who was the first President of the United States?",["Abraham Lincoln","Benjamin Franklin","George Washington"],2),
("Which empire was known as the largest land empire in history?",["Roman Empire","British Empire","Mongol Empire"],2),
("In which city was the Magna Carta signed?",["London","Runnymede","Oxford"],1),
("What was the name of the ship that sank on its maiden voyage in 1912?",["Britannic","Lusitania","Titanic"],2),
("Which civilisation built Machu Picchu?",["Aztec","Maya","Inca"],2),
("What language did the ancient Romans speak?",["Greek","Latin","Italian"],1),
("Who wrote 'The Art of War'?",["Confucius","Sun Tzu","Lao Tzu"],1),
("Which country was the first to give women the right to vote nationally?",["USA","New Zealand","UK"],1),
("In which country did the Renaissance begin?",["France","Spain","Italy"],2),
("What was the name of the first artificial satellite launched into space?",["Sputnik","Explorer","Vostok"],0),
("Which ancient civilisation built the Colosseum?",["Greek","Egyptian","Roman"],2),
("What was the capital of the Ottoman Empire?",["Cairo","Istanbul","Baghdad"],1),
("In what year did the Berlin Wall fall?",["1985","1989","1991"],1),
("Which explorer is credited with first circumnavigating the globe?",["Columbus","Magellan","Drake"],1),
("What was the name of the first European to reach India by sea?",["Vasco da Gama","Columbus","Marco Polo"],0),
("In which country is the ancient city of Petra located?",["Egypt","Jordan","Israel"],1),
("What was the name of the Cold War space race that landed humans on the moon?",["Apollo Program","Gemini Program","Mercury Program"],0),
("Which war was fought between the North and South of the United States?",["Revolutionary War","Civil War","War of 1812"],1),
("Who was the ancient Egyptian god of the sun?",["Osiris","Ra","Anubis"],1),
("What does the Latin phrase 'Veni, Vidi, Vici' mean?",["I came, I fought, I won","I came, I saw, I conquered","I lived, I loved, I lost"],1),
("In which century did the Industrial Revolution begin?",["17th century","18th century","19th century"],1),
("Which country did Napoleon Bonaparte come from originally?",["France","Italy","Corsica"],2),
("What was the name of the trade route connecting China to Europe?",["Spice Route","Silk Road","Golden Road"],1),
("Which ancient wonder of the world still exists today?",["The Hanging Gardens of Babylon","The Great Pyramid of Giza","The Colossus of Rhodes"],1),
("Who was the first person to walk in space?",["Yuri Gagarin","Alexei Leonov","Neil Armstrong"],1),
("What did the Aztecs call their capital city?",["Texcoco","Tenochtitlan","Tula"],1),
("During which war was the Battle of Waterloo fought?",["World War I","The Napoleonic Wars","The Seven Years War"],1),
]

WYR=[
("Live as a Roman gladiator for one year","Live as a medieval knight for one year"),
("Witness the building of the Great Pyramid","Witness the construction of the Eiffel Tower"),
("Meet Julius Caesar","Meet Cleopatra"),
("Explore ancient Rome at its peak","Explore ancient Egypt at its peak"),
("Be a crew member on Columbus's voyage to America","Be a crew member on Magellan's first circumnavigation"),
("Attend the original Olympic Games in ancient Greece","Attend the first modern Olympics in 1896 Athens"),
("Have studied under Aristotle","Have studied under Leonardo da Vinci"),
("Live through the Renaissance in Florence","Live through the Roaring Twenties in Paris"),
("Have been a member of the Spartan army","Have been a member of the Samurai class"),
("Be present at the signing of the Magna Carta","Be present at the signing of the Declaration of Independence"),
("Have sailed with the Vikings","Have marched with the Roman legions"),
("Live during the golden age of ancient Greece","Live during the golden age of the Islamic Golden Age"),
("Read the first ever printed book","Witness the first flight at Kitty Hawk"),
("Be a scribe in ancient Egypt","Be a philosopher in ancient Athens"),
("Attend a Shakespeare play in the original Globe Theatre","Attend the premiere of Beethoven's Ninth Symphony"),
("Discover a lost ancient civilisation","Decipher an undeciphered ancient script"),
("Have designed the Colosseum","Have designed the Great Wall of China"),
("Be a merchant on the Silk Road","Be a merchant in a medieval European trade fair"),
("Live in a medieval castle","Live in an ancient Roman villa"),
("Be a court painter for King Louis XIV","Be a court poet for Queen Elizabeth I"),
("Witness the fall of Constantinople","Witness the fall of the Berlin Wall"),
("Cook for a medieval king","Cook for an ancient Roman emperor"),
("Experience the French Revolution","Experience the American Revolution"),
("Have been an astronomer in ancient Babylon","Have been a mathematician in ancient Alexandria"),
("Sail on the Nile in ancient Egypt","Sail on the Thames in Tudor England"),
("Be an advisor to Napoleon","Be an advisor to Genghis Khan"),
("Speak every language of the ancient world","Read every book ever written in the ancient world"),
("Travel the Silk Road by camel","Travel the ancient Inca road by foot"),
("Be a page at King Arthur's court (if it were real)","Be a squire to a real medieval knight"),
("Find a complete set of Shakespeare's lost plays","Find a complete library of ancient Alexandria"),
]

if __name__=="__main__":
    print("FoF:",len(FACT_OR_FAKE),"| Quiz:",len(QUIZZES),"| WYR:",len(WYR))
