# MONTH 7 — Science & Nature themed Shorts content

FACT_OR_FAKE=[
("A day on Mercury lasts longer than a year on Mercury.",True,"Mercury rotates so slowly that one day takes 176 Earth days, while its year is only 88 Earth days."),
("The human body contains enough carbon to make about 9,000 pencils.",True,"The carbon in the human body, if extracted, would fill thousands of pencils."),
("Hot water freezes faster than cold water under some conditions.",True,"This is called the Mpemba effect, observed and studied since ancient times."),
("The sun makes up about 99.8% of the total mass of our solar system.",True,"Almost all the mass in our solar system is concentrated in the sun."),
("Sound travels faster through water than through air.",True,"Sound moves about 4.3 times faster in water than in air due to water's density."),
("All mammals can swim instinctively from birth.",False,"Many land mammals can swim without training, but not all — and some, like giraffes, struggle significantly."),
("A bolt of lightning contains enough energy to toast 100,000 slices of bread.",True,"A single lightning bolt carries roughly 250 kilowatt-hours of energy — enough to power a lot of toasters."),
("Octopuses have blue blood.",True,"Octopus blood contains hemocyanin (copper-based) rather than hemoglobin, making it blue."),
("The largest known star is about 100 times the size of our sun.",False,"The largest known stars (like UY Scuti) are over 1,700 times the radius of our sun."),
("Trees communicate with each other through underground fungal networks.",True,"Known as the 'Wood Wide Web', trees share nutrients and signals via mycorrhizal fungi."),
("Humans share about 60% of their DNA with bananas.",True,"This reflects common evolutionary building blocks shared across all life on Earth."),
("The Sahara Desert was once covered in grassland and lakes.",True,"Around 6,000–10,000 years ago, the Sahara experienced a 'Green Sahara' period with rivers and wildlife."),
("Water can exist in three states but not simultaneously.",False,"The triple point of water allows it to exist as solid, liquid, and gas simultaneously at a specific temperature and pressure."),
("Sharks are older than trees as a species.",True,"Sharks have existed for roughly 450 million years; trees only appeared about 360 million years ago."),
("Humans have a stronger sense of smell than dogs.",False,"Dogs have up to 300 million olfactory receptors vs. humans' 6 million, giving them a far superior sense of smell."),
("The moon is slowly moving away from Earth.",True,"The moon drifts about 3.8 cm farther from Earth each year due to tidal interactions."),
("Sunflowers track the sun throughout the day.",True,"Young sunflowers follow the sun (heliotropism); mature ones typically face east permanently."),
("Lightning strikes Earth about 100 times per second on average.",True,"Roughly 8 million lightning strikes hit Earth every day — that's about 100 per second."),
("The hardest natural material after diamond is graphene.",False,"After diamond, the next hardest natural mineral is generally moissanite (silicon carbide)."),
("The tongue is the strongest muscle in the human body.",False,"The masseter (jaw muscle) is often cited as the strongest by force; the tongue is not technically a single muscle."),
("The human eye can distinguish over 10 million different colors.",True,"The human visual system can theoretically distinguish between 10 million or more distinct colors."),
("Neutron stars are so dense that a teaspoon of their material weighs about a billion tons.",True,"Neutron star matter is extraordinarily compressed — a teaspoon would weigh about 10 million tons."),
("Cats always land on their feet due to a reflex called 'aerial righting'.",True,"Cats have a 'righting reflex' that allows them to rotate mid-fall to land feet first."),
("Glass is technically a very slow-moving liquid.",False,"This is a popular myth; old glass being thicker at the bottom is due to manufacturing, not flow."),
("Honey bees must visit approximately 2 million flowers to make one pound of honey.",True,"Bees travel enormous cumulative distances and visit millions of flowers to produce honey."),
("There are more atoms in a glass of water than glasses of water in all Earth's oceans.",True,"A glass of water contains roughly 10²⁵ molecules — far more than the number of glassfuls in all the oceans."),
("A mitochondrion can make copies of itself independently of the cell.",True,"Mitochondria have their own DNA and divide independently, supporting the endosymbiotic theory of their origin."),
("The Earth's inner core rotates slightly faster than the rest of the planet.",True,"Scientific studies suggest the inner core rotates at a slightly different rate than the outer layers."),
("Elephants are the only animals that cannot jump.",False,"Many animals cannot jump, including hippos, rhinos, and sloths — not just elephants."),
("Human fingernails grow faster on the dominant hand.",True,"Research shows nails grow slightly faster on the hand you use more, likely due to increased blood flow."),
]

QUIZZES=[
("What is the powerhouse of the cell?",["Nucleus","Mitochondria","Ribosome"],1),
("Which force causes tides on Earth?",["Solar wind","Gravity from the Moon","Earth rotation"],1),
("What is the chemical formula for water?",["HO","H2O","H2O2"],1),
("What force keeps planets in orbit around the sun?",["Magnetism","Friction","Gravity"],2),
("What is the speed of light in a vacuum (approximately)?",["300,000 km/s","150,000 km/s","450,000 km/s"],0),
("Which element has the atomic number 6?",["Nitrogen","Carbon","Oxygen"],1),
("What is the process by which plants make food using sunlight?",["Respiration","Photosynthesis","Transpiration"],1),
("What is the most abundant gas in Earth's atmosphere?",["Oxygen","Carbon dioxide","Nitrogen"],2),
("What organ pumps blood around the human body?",["Liver","Lungs","Heart"],2),
("Which is the largest planet in our solar system?",["Saturn","Jupiter","Uranus"],1),
("What force opposes motion between two surfaces in contact?",["Gravity","Friction","Tension"],1),
("What is the center of an atom called?",["Electron","Nucleus","Proton"],1),
("What is the name of the process by which cells divide?",["Mitosis","Osmosis","Meiosis"],0),
("What is the approximate temp at the centre of the sun?",["1 million°C","15 million°C","100,000°C"],1),
("What is the boiling point of water at sea level in Celsius?",["90°C","100°C","110°C"],1),
("What do you call animals that eat only plants?",["Carnivores","Herbivores","Omnivores"],1),
("What is the process of a solid turning directly into gas?",["Evaporation","Condensation","Sublimation"],2),
("What does a seismometer measure?",["Wind speed","Earthquakes","Air pressure"],1),
("What gas do plants absorb during photosynthesis?",["Oxygen","Carbon dioxide","Nitrogen"],1),
("Which part of the brain controls balance and coordination?",["Cerebrum","Cerebellum","Brainstem"],1),
("What is the name of the force that causes objects to fall toward Earth?",["Momentum","Gravity","Inertia"],1),
("What is DNA an abbreviation for?",["Deoxyribonucleic acid","Dinucleotide acid","Double nucleic acid"],0),
("Which organ is responsible for filtering blood in humans?",["Liver","Kidneys","Spleen"],1),
("How long does it take light from the sun to reach Earth?",["About 1 minute","About 8 minutes","About 1 hour"],1),
("What is the name of the layer of Earth's atmosphere that protects us from UV rays?",["Troposphere","Ozone layer","Ionosphere"],1),
("What is the chemical symbol for gold?",["Go","Gd","Au"],2),
("Which gas makes up most of the sun?",["Helium","Hydrogen","Oxygen"],1),
("What type of energy does a stretched spring have?",["Kinetic energy","Thermal energy","Potential energy"],2),
("What do you call the process by which water vapor turns into liquid?",["Evaporation","Condensation","Sublimation"],1),
("Which scientist developed the theory of evolution by natural selection?",["Isaac Newton","Charles Darwin","Gregor Mendel"],1),
]

WYR=[
("Be able to see in the dark like a cat","Have the hearing range of a bat"),
("Breathe underwater indefinitely","Survive in space without a suit"),
("Be immune to all diseases","Never need to sleep"),
("Have photosynthesis ability like a plant","Be able to echolocate like a dolphin"),
("Know exactly what the weather will be every day","Control the weather yourself"),
("Have the strength of an ant relative to your body size","Have the speed of a cheetah"),
("Only eat raw food forever","Only drink water — no other beverages"),
("Have perfect 20/20 vision with no glasses","Have perfect 20/20 hearing with no aid"),
("Live on the moon","Live under the sea"),
("Have a sixth sense for danger","Have an eighth sense for finding lost things"),
("Be able to regrow limbs like a salamander","Have the healing speed of a flatworm"),
("Never get sunburned","Never get a cold"),
("Have the memory of an elephant","Have the strength of a gorilla"),
("Know the exact cause of every illness you get","Know exactly how to cure it"),
("Be able to survive extreme cold","Be able to survive extreme heat"),
("Have the lifespan of a tortoise","Have the energy level of a hummingbird"),
("Have the navigation sense of a bird","Have the sense of smell of a bear"),
("Hibernate for 6 months like a bear","Only need 2 hours of sleep per night"),
("Be able to hold your breath for 20 minutes","Be able to run 100km without stopping"),
("Have the camouflage ability of a cuttlefish","Have the bioluminescence of a deep-sea fish"),
("Only eat things you grow yourself","Only eat things prepared by professional chefs"),
("Be able to survive a year with no food","Be able to survive a year with no sunlight"),
("Have a perfect internal clock, never late","Have perfect spatial awareness, never lost"),
("Spend a month on the International Space Station","Spend a month at a deep-ocean research station"),
("Have bones as light as a bird's","Have skin as tough as a crocodile's"),
("See ultraviolet light like a bee","Hear infrasound like an elephant"),
("Have the regeneration ability of a starfish","Have the immunity of a naked mole rat"),
("Explore a newly discovered cave system","Explore a newly discovered ocean trench"),
("Know every species of animal by sight","Know every species of plant by sight"),
("Live in a rainforest for a year","Live in an arctic tundra for a year"),
]

if __name__=="__main__":
    print("FoF:",len(FACT_OR_FAKE),"| Quiz:",len(QUIZZES),"| WYR:",len(WYR))
