# MONTH 9 — 90s Nostalgia

FACT_OR_FAKE=[
("The first text message ever sent said 'Merry Christmas'.",True,"Neil Papworth sent 'Merry Christmas' to Vodafone director Richard Jarvis on 3 December 1992."),
("Tamagotchis were invented in Japan in the 1990s.",True,"Bandai released the Tamagotchi in Japan in 1996, creating a global virtual pet craze."),
("The Lion King was the first Disney film based on an original story.",False,"Many Disney films before it were original stories; The Lion King was also heavily inspired by Shakespeare's Hamlet and a Japanese anime."),
("The Spice Girls sold more albums in the 1990s than any other female group in history.",True,"Wannabe debuted at number one in 37 countries and the group became the best-selling female group of all time."),
("The first Harry Potter book was rejected by 12 publishers before being accepted.",True,"J.K. Rowling faced multiple rejections before Bloomsbury published Harry Potter and the Philosopher's Stone in 1997."),
("The PlayStation 1 was originally designed as a CD-ROM add-on for the Super Nintendo.",True,"Sony developed it in partnership with Nintendo before the deal fell through, leading to the standalone PlayStation."),
("Friends was the highest-rated TV show of the entire 1990s decade.",False,"ER was actually the top-rated show for most of the 90s, though Friends was hugely popular."),
("The internet was available to the public before the 1990s.",True,"The World Wide Web was invented in 1989 and became publicly available in 1991, though widespread home use exploded in the mid-90s."),
("Kurt Cobain named Nirvana after a Buddhist concept meaning transcendence.",True,"Cobain confirmed he chose the name for its spiritual connotation of freedom from suffering."),
("Space Jam featured Michael Jordan's actual basketball skills motion-captured for the animated scenes.",False,"Space Jam used traditional animation; motion capture technology wasn't used for Jordan in that film."),
("The first Google search engine was launched from a garage in 1998.",True,"Larry Page and Sergey Brin launched Google in 1998, initially working out of a garage in Menlo Park."),
("Furby was originally designed for the Japanese market.",False,"Furby was an American creation by Tiger Electronics, first released in 1998 and then sold worldwide."),
("The Hubble Space Telescope was launched in the 1990s.",True,"Hubble was launched on April 24, 1990, aboard the Space Shuttle Discovery."),
("Windows 95 sold more than a million copies in its first week.",True,"It sold around 7 million copies in the first five weeks — a record-breaking launch for software at the time."),
("The Mighty Morphin Power Rangers were originally a Japanese show.",True,"They were adapted from the Japanese 'Super Sentai' series, with new footage of American actors spliced in."),
("Titanic (1997) was the first film to earn $1 billion at the global box office.",True,"It became the highest-grossing film of all time at that point, earning over $1.8 billion globally."),
("The yo-yo was originally a weapon before it became a toy.",False,"Despite the popular story, there is no credible historical evidence that yo-yos were used as weapons."),
("Slap bracelets were banned in some US schools in the early 1990s.",True,"Multiple schools banned them after reports of children getting cuts from the exposed metal inside worn bracelets."),
("The first ever DVD movie released was Twister.",True,"Twister was the first DVD movie released in the United States in March 1997."),
("The 90s hit song 'Macarena' was originally a slow ballad.",True,"Los del Río originally recorded it as a slower, more traditional flamenco-pop song before it was remixed into the dance hit."),
("Beanie Babies were so popular in the 90s that people invested millions in them expecting them to gain value.",True,"The beanie baby craze led people to buy, collect, and store them in protective cases, expecting huge returns — most were ultimately worth very little."),
("The Goosebumps book series was created by R.L. Stine in the 1990s.",True,"R.L. Stine launched the Goosebumps series in 1992, and it became one of the best-selling book series of all time."),
("Bill Nye the Science Guy first aired on TV in 1993.",True,"Bill Nye the Science Guy premiered on September 10, 1993 on KCTS in Seattle."),
("The Backstreet Boys were put together through an open audition in New York.",False,"They were formed in Orlando, Florida in 1993 through connections made by businessman Lou Pearlman."),
("Pokémon was originally called 'Capsule Monsters'.",True,"Creator Satoshi Tajiri originally proposed the concept under the working title 'Capsule Monsters' before it became Pocket Monsters/Pokémon."),
("The Matrix was the first film to use bullet-time photography.",True,"The Wachowskis pioneered the technique for The Matrix (1999) using dozens of still cameras firing in sequence."),
("The original Game Boy had a color screen.",False,"The original Game Boy, released in 1989, had a distinctive yellow-green monochrome screen. The Game Boy Color didn't arrive until 1998."),
("AOL Instant Messenger launched in the 1990s.",True,"AIM launched in 1997 and became one of the dominant ways people communicated online through the late 90s and 2000s."),
("Shrek was originally planned as a 2D animated film.",True,"DreamWorks initially developed Shrek as a 2D film before switching to 3D CGI animation."),
("Fresh Prince of Bel-Air's theme song was improvised by Will Smith in under an hour.",True,"Smith has claimed he wrote and recorded the theme song in about an hour during a studio session."),
]

QUIZZES=[
("Which band sang 'Wannabe' in 1996?",["Destiny's Child","TLC","Spice Girls"],2),
("Which animated movie features a lion cub named Simba?",["The Jungle Book","Tarzan","The Lion King"],2),
("What was the name of the virtual pet toy craze of the late 90s?",["Furby","Tamagotchi","Neopet"],1),
("In which year did Titanic (the film) release?",["1995","1997","1999"],1),
("Which console was released by Sony in 1994/1995?",["Nintendo 64","Sega Saturn","PlayStation"],2),
("Who played Will Smith's character in 'The Fresh Prince of Bel-Air'?",["DJ Jazzy Jeff","Will Smith","James Avery"],1),
("What did the acronym WWW stand for in the 90s internet boom?",["World Wide Web","Wide Wire Wiring","World Web Works"],0),
("Which 90s toy involved collecting small round cards and flipping them?",["Pogs","Marbles","Trading cards"],0),
("What was the name of the loveable purple dinosaur from the 90s kids TV show?",["Barney","Rex","Dino"],0),
("Which 1999 film starred Keanu Reeves as 'Neo'?",["The Matrix","Speed","Point Break"],0),
("What type of pet was the Tamagotchi?",["A digital alien","A virtual pet","A robotic dog"],1),
("Who sang 'Baby One More Time' in 1998?",["Christina Aguilera","Britney Spears","Jennifer Lopez"],1),
("Which TV show featured the characters Ross, Rachel, Monica, Chandler, Joey, and Phoebe?",["Seinfeld","Friends","Frasier"],1),
("What is the name of the Toy Story cowboy?",["Buzz","Rex","Woody"],2),
("Which 90s boy band included members JC Chasez and Justin Timberlake?",["Backstreet Boys","New Kids on the Block","NSYNC"],2),
("What year did the Pokémon Trading Card Game first release?",["1993","1996","1999"],1),
("Which film featured the line 'You had me at hello'?",["Notting Hill","Jerry Maguire","Pretty Woman"],1),
("What was the most popular search engine before Google dominated?",["Yahoo","AOL","AltaVista"],0),
("Which Nirvana album featured the song 'Smells Like Teen Spirit'?",["In Utero","Bleach","Nevermind"],2),
("What classic board game released a CD-ROM version in the 90s to capitalise on the tech boom?",["Scrabble","Monopoly","Trivial Pursuit"],1),
("Which 90s animated series featured the Rugrats characters?",["Hey Arnold","Rugrats","Doug"],1),
("What handheld gaming device did Nintendo release in 1989 (popular throughout the 90s)?",["Game Gear","Lynx","Game Boy"],2),
("Which famous grunge band was formed in Seattle in 1987?",["Pearl Jam","Soundgarden","Nirvana"],2),
("What was the name of the robot toy that could interact and learn from children?",["Furby","Tamagotchi","Aibo"],0),
("Which 1990 film featured Macaulay Culkin as a boy left home alone at Christmas?",["Home Alone","My Girl","The Good Son"],0),
("What color were the original Gameboy's graphics?",["Black and white","Green monochrome","Amber"],1),
("Which rapper released 'The Chronic' in 1992?",["Tupac","Snoop Dogg","Dr. Dre"],2),
("What 90s dance craze involved putting hands on hips and wiggling?",["Electric Slide","The Macarena","The Running Man"],1),
("Which 1993 film featured a T-Rex and velociraptors in a theme park?",["Jurassic Park","Congo","The Lost World"],0),
("Who wrote the Harry Potter series that began in 1997?",["Roald Dahl","J.K. Rowling","Philip Pullman"],1),
]

WYR=[
("Have grown up in the 90s with no internet","Have grown up now with full internet access"),
("Own an original collection of first-edition Pokémon cards","Own a collection of every Beanie Baby ever made"),
("Watch every episode of Friends for the first time","Watch every episode of The Fresh Prince for the first time"),
("Have been backstage at a Spice Girls concert","Have been backstage at a Nirvana concert"),
("Have a working original Game Boy with all your favourite games","Have a modern Nintendo Switch with all current games"),
("Relive the day the internet became available in your home","Relive the first time you watched a VHS that was finally rewound"),
("Attend the premiere of The Lion King in 1994","Attend the premiere of Titanic in 1997"),
("Win a lifetime supply of Dunkaroos","Win a lifetime supply of Gushers"),
("Have been in the audience for TRL on MTV","Have been in the audience for a 90s game show"),
("Only use a 90s mobile phone for a year","Only use a 90s desktop computer for a year"),
("Have owned the first PlayStation on launch day","Have owned a Nintendo 64 on launch day"),
("Spend a week in 1999 New York City","Spend a week in 1999 London"),
("Have a 90s childhood bedroom exactly as you'd have wanted it","Have a 90s childhood wardrobe exactly as you'd have wanted it"),
("Only listen to 90s music for a year","Only watch 90s TV for a year"),
("Be able to say you discovered Pokémon before it was cool","Be able to say you discovered the internet before it was mainstream"),
("Own every 90s video game console","Own every 90s action figure collection"),
("Have been a student when Harry Potter first came out","Have been a student when The Matrix first came out"),
("Spend a day at a 90s school","Spend a day at a 90s shopping mall"),
("Have the 90s internet at its speed for life","Have no internet but every 90s video game ever made"),
("Relive the first time you heard your favourite 90s song","Relive the first time you watched your favourite 90s film"),
("Get a message on AIM from your favourite 90s celebrity","Get a fax from your favourite 90s celebrity"),
("Watch the Super Bowl halftime shows of the 90s all in a row","Watch the MTV Video Music Awards of the 90s all in a row"),
("Have been a cast member on Saved by the Bell","Have been a cast member on Baywatch"),
("Own an original Air Jordan from the 90s in your exact size","Own an original pair of Doc Martens from the 90s in your exact size"),
("Have one day to live your best 90s kid life","Have one week to live your best 90s teen life"),
("Be able to go back and buy Apple stock in 1997","Be able to go back and buy Amazon stock in 1997"),
("Spend a summer at a 90s summer camp","Spend a summer at a 90s theme park"),
("Have perfect memory of every 90s cartoon you watched","Have perfect memory of every 90s video game you played"),
("Meet the Spice Girls in 1997","Meet the Backstreet Boys in 1999"),
("Have been a 90s kid in the USA","Have been a 90s kid in the UK"),
]

if __name__=="__main__":
    print("FoF:",len(FACT_OR_FAKE),"| Quiz:",len(QUIZZES),"| WYR:",len(WYR))
