# MONTH 11 — Christmas & Holidays Special

FACT_OR_FAKE=[
("Santa Claus's red suit was created by Coca-Cola's advertising team.",False,"The red suit predates Coca-Cola's 1930s ads — it was popularized by earlier illustrators like Thomas Nast in the 19th century."),
("Christmas was once banned in England.",True,"Under Oliver Cromwell in the 1640s and 1650s, Christmas celebrations were illegal in England."),
("The first Christmas card was sent in 1843.",True,"Sir Henry Cole commissioned the first commercial Christmas card in 1843 in England."),
("Rudolph the Red-Nosed Reindeer was originally created by a department store.",True,"Rudolph was created in 1939 by Robert L. May for Montgomery Ward stores as a holiday promotional giveaway."),
("Christmas trees originated in Germany.",True,"The tradition of decorating Christmas trees originated in Germany in the 16th century and spread globally."),
("Jingle Bells was originally written as a Thanksgiving song.",True,"James Lord Pierpont wrote it in 1857 for a Thanksgiving celebration — the lyrics reference horse racing, not Christmas."),
("The world's tallest Christmas tree ever displayed was over 200 feet tall.",True,"A Douglas fir displayed in a Washington state shopping center in 1950 measured 221 feet."),
("Boxing Day gets its name from boxing matches held on the 26th of December.",False,"Boxing Day likely comes from the tradition of giving gift boxes to servants or tradespeople, not from the sport."),
("In Japan, it's traditional to eat KFC for Christmas.",True,"A 1974 marketing campaign turned KFC into a beloved Japanese Christmas tradition — orders are placed months in advance."),
("Candy canes were invented to keep children quiet in church during long Christmas services.",True,"One account traces the origin to a choirmaster at Cologne Cathedral in Germany who gave sugar sticks to children."),
("The famous Christmas song 'White Christmas' was written by a Jewish songwriter.",True,"Irving Berlin, who was Jewish, wrote 'White Christmas' — still the best-selling single of all time."),
("The tradition of leaving out milk and cookies for Santa comes from Norse mythology.",False,"The most likely origin is Dutch and Scandinavian traditions of leaving out food for Odin's horse, Sleipnir."),
("Eggnog originated in North America in the 1700s.",True,"Eggnog developed in early America from British milk-and-ale drinks like posset, with rum replacing ale."),
("In Australia, Christmas falls during summer.",True,"Australia is in the Southern Hemisphere, so December 25 is in the middle of their summer."),
("The song 'Happy Birthday to You' earns more royalties than any Christmas song annually.",True,"Until it entered the public domain in 2016, 'Happy Birthday' consistently earned more royalties than seasonal songs."),
("Santa Claus is based on a real historical person.",True,"Santa Claus is based on Saint Nicholas of Myra, a 4th-century Christian bishop known for generosity."),
("Hanukkah always falls on the same date in December.",False,"Hanukkah follows the Hebrew calendar and can fall anywhere from late November to late December."),
("The Christmas stocking tradition comes from a story about Saint Nicholas throwing gold coins.",True,"Legend says Saint Nicholas tossed bags of gold through a window, landing in stockings hung to dry."),
("Mistletoe was considered sacred by the ancient Celts and Norse.",True,"Both cultures considered mistletoe a powerful symbol of peace, love, and protection."),
("Christmas became a federal holiday in the USA in 1870.",True,"President Ulysses S. Grant signed Christmas into law as a US federal holiday on June 28, 1870."),
("The traditional 12 Days of Christmas start on Christmas Day.",False,"Traditionally the 12 Days of Christmas begin on December 25 and end on January 5 (Twelfth Night)."),
("Poinsettias are poisonous to humans.",False,"They can cause mild stomach upset, but poinsettias are not dangerously toxic to humans, though they can be irritating."),
("The world's most expensive Christmas tree was decorated with diamonds and cost over $11 million.",True,"A tree in Abu Dhabi in 2010 was decorated with $11 million worth of jewels and ornaments."),
("Elves are a traditional part of Scandinavian Christmas folklore.",True,"Tomte or Nisse — small elf-like figures — have been part of Scandinavian Christmas tradition for centuries."),
("Christmas was not widely celebrated in America until the mid-1800s.",True,"Puritan influence suppressed Christmas celebration in early America; it only gained wider popularity after the 1820s–1840s."),
("Tinsel was originally made of real silver.",True,"Tinsel was first made from thin strips of hammered real silver in Germany in the 17th century."),
("The Christmas cracker was invented by a British confectioner in the 1840s.",True,"Tom Smith invented the Christmas cracker in 1847, inspired by French bonbons wrapped in paper."),
("Reindeer are real animals and both males and females can grow antlers.",True,"Rangifer tarandus is a real animal; uniquely among deer, females also grow antlers."),
("In Iceland, 13 different Santas (called Yule Lads) visit children in December.",True,"Icelandic Christmas folklore includes 13 Yule Lads, each with a different mischievous trait."),
("The date December 25 was chosen for Christmas because it was the known birth date of Jesus.",False,"No historical record confirms Jesus's birth date; December 25 was likely chosen to coincide with existing winter solstice celebrations."),
]

QUIZZES=[
("In the song 'The Twelve Days of Christmas', how many lords are a-leaping?",["10","11","12"],0),
("Which country started the tradition of the Christmas tree?",["England","USA","Germany"],2),
("What is the traditional Christmas plant with red and green leaves?",["Holly","Poinsettia","Mistletoe"],1),
("Which three gifts did the Biblical Magi bring?",["Gold, frankincense, myrrh","Silver, spice, amber","Diamond, silk, ivory"],0),
("In Charles Dickens' A Christmas Carol, what is Scrooge's first name?",["Edgar","Ebenezer","Edmund"],1),
("In which country does the Christmas celebration of 'La Posada' originate?",["Spain","Cuba","Mexico"],2),
("What is Hanukkah also commonly called?",["Festival of Lights","Festival of Stars","Festival of Colors"],0),
("How many reindeer does Santa traditionally have including Rudolph?",["8","9","10"],1),
("Which country is credited with sending the first Christmas card?",["USA","Germany","England"],2),
("What is the main religion associated with Diwali?",["Islam","Hinduism","Buddhism"],1),
("What do children in the Netherlands leave out for Sinterklaas's horse?",["Sugar cubes","Carrots","Hay"],2),
("Which holiday, celebrated on December 26 to January 1, is an African American celebration of culture and values?",["Kwanzaa","Juneteenth","Heritage Day"],0),
("In the film 'Elf', where does Buddy the Elf travel to find his father?",["Los Angeles","Chicago","New York City"],2),
("What is the Christian festival celebrated 12 days after Christmas called?",["Epiphany","Advent","Candlemas"],0),
("Which Scandinavian myth explains the tradition of decorating a Christmas tree?",["The Yggdrasil world tree","Odin's spear","Thor's hammer"],0),
("What are the origins of the word 'Yule'?",["A Norse word for winter feast","A Roman word for fire","A Celtic word for sun"],0),
("In Australia, which bird is commonly depicted instead of robins on Christmas cards?",["Kookaburra","Emu","Cockatoo"],0),
("On what date do Spanish-speaking countries traditionally open presents?",["December 25","December 31","January 6"],2),
("What is the Italian Christmas dessert that is shaped like a dome and contains dried fruit?",["Tiramisu","Panettone","Cannoli"],1),
("Which classic Christmas film features the character Kevin McCallister?",["Home Alone","A Christmas Story","National Lampoon's Christmas"],0),
("In Germany, what is the Advent calendar used to count down to?",["New Year's Day","Christmas Day","Epiphany"],1),
("Which carol begins with the line 'Silent night, holy night'?",["Silent Night","O Holy Night","Away in a Manger"],0),
("In the UK, what is the traditional December 26th public holiday called?",["St Stephen's Day","Boxing Day","Winter Bank Holiday"],1),
("What vegetable is traditionally served with Christmas dinner in the UK?",["Parsnips","Brussels sprouts","Carrots"],1),
("Which Christmas song begins 'Oh the weather outside is frightful'?",["Frosty the Snowman","Let It Snow","Winter Wonderland"],1),
("What is the French Christmas log cake dessert called?",["Galette des Rois","Bûche de Noël","Kouign-Amann"],1),
("In 'It's a Wonderful Life', who is George Bailey's guardian angel?",["Gabriel","Clarence","Michael"],1),
("Which country decorates streets with 'luminarias' (small paper lantern bags) at Christmas?",["Mexico","Brazil","Argentina"],0),
("What shape is a traditional Christmas Stollen bread?",["A wreath","A swaddled baby","A star"],1),
("In Finland, where does Santa Claus officially live according to Finnish tradition?",["The North Pole","Lapland","Rovaniemi"],2),
]

WYR=[
("Have Christmas last a full week","Have Christmas come twice a year"),
("Be able to eat all the Christmas food with no consequences","Be able to give the perfect gift to everyone you love"),
("Wake up to a snowy Christmas every year","Wake up to a warm sunny Christmas every year"),
("Watch every Christmas film in one sitting","Listen to Christmas music all year round"),
("Spend Christmas Day in New York City","Spend Christmas Day in Lapland, Finland"),
("Have a real Christmas tree every year","Have a perfect artificial tree that looks completely real"),
("Be the person who wraps all the gifts perfectly","Be the person who always picks the perfect gifts"),
("Experience Christmas as a child again","Experience Christmas for the first time as an adult"),
("Live in a house decorated like the Griswolds in Christmas Vacation","Live in a house with minimal but perfectly elegant decorations"),
("Only ever receive practical gifts","Only ever receive fun gifts with no practical value"),
("Cook Christmas dinner for 20 people","Attend Christmas dinner cooked by someone else for 20 people"),
("Have the ability to make it snow on demand","Have the ability to guarantee perfect Christmas Day weather"),
("Spend Boxing Day shopping the sales","Spend Boxing Day completely off-grid with no shopping"),
("Only watch Christmas movies for the entire month of December","Only listen to Christmas music for the entire month of December"),
("Have a Scrooge-style ghost visit showing your Christmas past","Have a ghost visit showing your ideal Christmas future"),
("Receive one incredibly expensive gift","Receive 20 thoughtful smaller gifts"),
("Send a personalised Christmas card to every person you know","Receive a personalised card from every person you know"),
("Be in charge of all Christmas decorations at home","Be in charge of all Christmas cooking"),
("Celebrate Christmas in a tropical location","Celebrate Christmas in a snowy mountain chalet"),
("Have every Christmas song ever made on a playlist","Have every Christmas film ever made on a streaming service"),
("Spend Christmas morning in pyjamas all day","Have a formal Christmas dinner in your finest clothes"),
("Open all presents on Christmas Eve","Open all presents on Christmas morning"),
("Have access to every Christmas market in Europe for one day","Have access to the best Christmas lights display in the world for one night"),
("Have a completely stress-free Christmas with strangers","Have a wonderful but slightly chaotic Christmas with family"),
("Spend New Year's Eve at a huge party with thousands","Spend New Year's Eve in an intimate gathering with close friends"),
("Have unlimited Christmas budget but have to buy everything on Christmas Eve","Have a strict budget but start shopping in September"),
("Get to experience Christmas traditions from every country in one day","Get to experience the world's most magical Christmas market"),
("Always know what everyone wants for Christmas","Always find the perfect gift without knowing what they want"),
("Have a real life Elf-on-the-Shelf that genuinely plays pranks","Have a real life Rudolph that glows and guides Santa"),
("Experience Christmas exactly as Dickens described it in Victorian England","Experience Christmas exactly as it would have been in 1960s suburban America"),
]

if __name__=="__main__":
    print("FoF:",len(FACT_OR_FAKE),"| Quiz:",len(QUIZZES),"| WYR:",len(WYR))
